### ISSUE TITLE
Rank issue

### ISSUE THREAD

**Issue by Djmaks6681** [o5k/tetrio-issues#1288]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Firefox 125

### Describe the bug/issue

I played 43 tetra league matches.  1 year ago when i played 10 matches it gave me my rank. when I came back to tetr.io Instead of showing my previous rank it shows me a "?" I played a couple of matches but it didn't help.

### Expected behavior

It should update my rank or give me my previous one.

### Screenshots

![Screenshot 2024-04-18 153943](https://github.com/tetrio/issues/assets/167441290/336b158d-f7cd-4572-a4e6-12a8997b5e7f)

**Comment by ZaptorZap** [comment]
This is due to [Rating Deviation](https://tetrio.github.io/faq/mechanics.html#rd). It's considered a fundamental concept of [Glicko-2](https://en.wikipedia.org/wiki/Glicko_rating_system#Glicko-2_algorithm).

Since you have `101` Rating Deviation left, I presume you'll get your rank back once you've completed one more game.
