### ISSUE TITLE
Seperate Slider for sfx and volume control

### ISSUE THREAD

**Issue by ace787b** [o5k/tetrio-issues#1310]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I'm always frustrated when i try to use the scroll wheel to adjust sfx with my own songs in the background, because scrolling up also increases the ingame music. 

### Describe the solution you'd like

holding a certain key while scrolling to adjust only sfx, and hitting another key to adjust only music

### Describe alternatives you've considered

just muting the game, but i wanna hear the thunder whenever i get a nice combo going.

**Comment by ZaptorZap** [comment]
You can hover over the SFX slider with your mouse to only effect that already. I don't think more bindings to worry about makes sense here, but a way to lock the volume in the config itself makes sense to me. (you could even technically remove the "scroll to change volume" toggle, since locking both sliders would effectively disable scrolling to change volume)

**Comment by ace787b** [comment]
> You can hover over the SFX slider with your mouse to only effect that already. I don't think more bindings to worry about makes sense here, but a way to lock the volume in the config itself makes sense to me. (you could even technically remove the "scroll to change volume" toggle, since locking both sliders would effectively disable scrolling to change volume)

i didn't know that
