### ISSUE TITLE
Finesse, KPP and 'Detail oriented' achievement are broken

### ISSUE THREAD

**Issue by lahoyasrha** [o5k/tetrio-issues#1352]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Mac OS Sonoma 14.2.1

### Browser and version

Chrome 127.0.6533.89 (official build) (x86_64)

### Describe the bug/issue

You will be able to see this with this replay example: https://tetr.io/#R:e8f7cfc5d0cc
- No KPP on left or right moves
- No finesse fault at 1:04.000 despite there obviously is big mistake
- As a consequence, the 'Detail oriented' leaderboard features players who performed incredible <80 moves Sprints!

By the way, thanks for all the hard work guys!
Honestly, Zenith tower is the greatest thing that happened to Tetris World since Tetr.io itself!

### Expected behavior

Any key press should count!

### Screenshots

![TETR-IO](https://github.com/user-attachments/assets/b167c121-fe7e-4135-a545-ac3a04c7dcb8)

### Console logs

N/A

**Comment by ZaptorZap** [comment]
Thanks for the report. There's no issue here because these players are simply **holding** both the left movement and the right movement the entire run. TETR.IO switches between which one is the active movement by considering the last movement pressed(so long as you haven't let go—so strictly speaking, this player presses and holds `←` the entire run).

I went ahead and looked into it and it appears as though the replay correctly specifies how many inputs were pressed. Replays are just `.json` files that specify keypresses, which TETR.IO's deterministic engine correctly plays back.
![image](https://github.com/user-attachments/assets/7e334f24-a151-4dcf-be05-ff78df99fb05)

**Comment by ZaptorZap** [comment]
Oh—and as for Finesse, it's simply canceled when Soft Drop is involved, otherwise tucks are impossible to do without extensive planning/using technical definitions. If you're abusing this for 0 fault runs, you're really only cheating yourself.
