### ISSUE TITLE
Quick play Carrier best doesnt update after getting a new best score on desktop client or the webside profile .

### ISSUE THREAD

**Issue by KArlL0010** [o5k/tetrio-issues#1373]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Firefox 11.17.7

### Describe the bug/issue

In the desktop client and browser profile, after setting a new All time best score on quick play, Carrier best doesn't update, and instead acts as if it was a weekly best.

### Reproducing

1. Set a new all time best score on the Zenith tower
2. Check the in client Profile or the web profile

### Expected behavior

The Carrier best score should update when setting a new score that is higher then the previous score.

### Screenshots

![Screenshot 2024-08-30 050255](https://github.com/user-attachments/assets/e4d23256-a846-44b6-8f35-c0f9712f3eb2)
![Screenshot 2024-08-30 051142](https://github.com/user-attachments/assets/8883e699-8bdc-4ad0-aee5-39ec6645b858)

**Comment by ZaptorZap** [comment]
As unintuitive as it may seem, this is **by design**. Your _Career best_ only updates at the end of the week, as it is based on **your placement** in the final leaderboard for that week. For example, 1,023.9m(#​20,000th place) will be overridden by 935.1m (#​10,000th place). Since this cannot be determined until the week has ended, your previous best is shown for the duration of the entire week.

If you wish for this behavior to change, this would become a feature request, not a bug report. A core tenant of this philosophy is that designers wish for Quick Play to be fought between **players**, not the system. Weeks change often and the mode is very sensitive to whoever is playing.
