### ISSUE TITLE
A debugger statement is present in the code

### ISSUE THREAD

**Issue by ramzi-mrabet** [o5k/tetrio-issues#1418]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 130

### Describe the bug/issue

A debugger statement is present in the code, and it gets triggered when the developer tools is opened in inspect mode.

### Reproducing

Just open website and open the inspect

### Expected behavior

Opening the developer tools in inspect mode should not trigger any debugger statements or cause the code to pause unexpectedly.

### Screenshots

![image](https://github.com/user-attachments/assets/f516819a-7b32-45ab-a05b-faf11f21ee32)

**Comment by ZaptorZap** [comment]
This is by design. It's a very basic anti-tamper measure. If you want to argue for its removal, I'm afraid there's a bit of a precedence to keep it in. In any case, it's not a bug.

As far as console logs go, theoretically we expect you to open the console after unintended/relevant behavior occurs, which should still be logged even if the game isn't running.
