### ISSUE TITLE
180 Rotations

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#16]
Jstris speedplayers would like this added, might not be beginner-friendly

**Comment by o5k** [comment]
The game is very high-power as is, so I feel adding more tools will make it impossible for newcomers to play. Need opinions...

**Comment by daniel35489** [comment]
The lack of a proper 180 spin function is a bit off-putting for anybody transitioning from  jstris to tetr.io. While it would be slightly more difficult for those who don’t use 180 spin to fight those who do, it really doesn’t make such a huge difference that it’ll matter a whole bunch imo. It doesn’t matter if a 3 PPS player has access to 180 spins compared to a .5 PPS player. The .5 PPS player will lose regardless. Unless we divide the new players and the more experienced players, the experienced ones are always gonna be beating the newer ones. The feature is gonna be accessible to everyone so everyone is free to learn 180s. On the other hand without 180 spins it makes the transition from games with 180s difficult. Improving is one of the things that make Tetris fun and learning 180s is adding another layer to that too. Overall I think that it would help more to just add the 180 instead of ignoring it in order to shelter those who can’t be bothered to learn it.

**Comment by o5k** [comment]
How do you feel 180 should be implemented? Two rotations in a direction, or an entire new set of kicks?

**Comment by daniel35489** [comment]
Personally I would prefer the way that jstris dealt with 180 spins but that’s specifically my preference. But if we consider those that are used to 180 spins I feel like the majority would be coming off of Jstris anyway. Plus directional 180s could result in the position of pieces shifting which might give even more of an edge to players that 180. While I did say that it isn’t necessary to worry about the minimal advantage given by a 180. It’d still be nicer on the other side of the argument to make them limited in directionality so that it doesn’t provide an even bigger gap.

**Comment by julf0** [comment]
> How do you feel 180 should be implemented? Two rotations in a direction, or an entire new set of kicks?

We only need this
![180](https://user-images.githubusercontent.com/46527680/74654827-ef835900-5169-11ea-9633-b43756ea0a33.gif)

**Comment by alex-ong** [comment]
My argument is that tetrio is not jstris. tetrio is a clean game with very good core guideline gameplay and it is free from confusing (though admittedly fairer(?) game mechanics. E.g. tetrio doesn't have fractional garbage or send to all. 

There are two key implementations of 180 as mentioned before
a) Press rotate twice for you
b) New kicks.

Personally i find 180 degree kicks an even more confusing thing than even TST's. They add fake depth to the game (just adding more depth to the game isn't always good). From a balance perspective they don't really affect anything, probably only pc openers with the famous J/L case:
![](https://i.imgur.com/AKVtcnp.gif)

My reasons for no (a):
1) ccw and cw are different
2) It would be confusing if you evaluated kicks twice in one frame. E.g. imperial cross case. Since cw and ccw are different, Imperial cross teleportation is now assymetric.
3) You can get stuff like this based on implementation (is soft drop respected during rotation?):
![](https://i.imgur.com/M3EO7WH.gif)

My key reasons for no (b):
1) This is not jstris
2) 180's are confusing
3) There isn't a guideline implementation, so every game does it differently
4) Even if it was decided to (b), now we have another problem which is which set of kicks to use.

**Comment by o5k** [comment]
> There isn't a guideline implementation, so every game does it differently

This is a pretty important thing I feel.. The reason TETR.IO stays guideline is so that people have a lot of already-known techniques to learn. There's many videos on how kicks work, lots of articles about optimizing speed etc. Since 180 isn't standardized like that, it's a bit harder for me to add, because the implementation would cause confusion.

I'm also unsure what moves exactly it would allow. I guess it can fix mistakes, but other than that I'm worried of then having to nerf Perfect Clears, due to them becoming even more accessible to pros.

I'm very much on the fence here. It's something a lot of players want and request, but ultimately I'm unsure if it would improve the quality of the game.

**Comment by XDEmer0r-L0rd-360-G0d-SlayerXD** [comment]
In my experience of using 180 I end up using them only when attempting to salvage some mistake I've made. Using 180 as a macro for two rotations will have practically no impact in general game play because the time saved is not large enough to make up the difference in thinking speeds of different skill levels. The biggest reason I'm for 180s is because I find them even cooler than t-spins even if they aren't worth more. Personally I am of the opinion that having more options available, even if hidden or buried, are better in anything including Tetrio.

**Comment by PopMagoot** [comment]
The thing with 180 is that many players, including myself are coming from playing jstris or nullpomino very avidly and have become used to 180 spins. This not only affects your mindset as you're playing, knowing that certain mistakes are able to be fixed with 180 that wouldn't be possible without them, but also affects muscle memory and speed.  This makes it quite awkward to switch between tetr.io and jstris or nullpomino and may turn some players off from the site because their control scheme is being switched from what they are used to.

**Comment by alex-ong** [comment]
> The thing with 180 is that many players, including myself are coming from playing jstris or nullpomino very avidly and have become used to 180 rotations. This not only affects your mindset as you're playing, knowing that certain mistakes are able to be fixed with 180 that wouldn't be possible without them, but also affects muscle memory and speed.

nullpomino, cultris and jstris have different kick tables. If 180's with a new kick table in tetr.io were implemented, whichever kick table you choose you are screwing over the other two's "muscle memory and speed"

**Comment by daniel35489** [comment]
In that case wouldn’t it be easier to just implement the kick tables for all of them and let that be an adjustable setting? I mean easier on the player base not on osk. Sorry osk, this solution involves more work on ur side but in my eyes it’ll appeal to the majority of people in that case. If that were the case then what other objections do you have?

**Comment by alex-ong** [comment]
Sure, that's what jstris does, you can change kick tables (e.g. there's a troll one with o-spins) in rule settings. Though again this seems like additional complexity to a "clean" game.

**Comment by PopMagoot** [comment]
I say just use the jstris table because I believe its the most popular client with 180s right now.

**Comment by tetris28** [comment]
180 spins have always been a hot issue. Back in the day nullpomino allowed custom rulesets. The main popular rulesets had some very aggressive 180 spin kicks, including the ones XeaL showed in his gifs above. The community argued back and forth about the merits of the kicks and the majority of people settled on the simplified 180 kicks implemented by myndzi for king of stackers (KoS). These kicks excluded any teleports and involved just natural 180 spins like the ones shown by julf. When jez began implementing the 180 kicks in jstris we pressured him not to take it too extreme and he settled on using pretty much the same kick table as KoS. If you go in the direction of implementing 180 kicks, I would urge you to follow either KoS or Jstris 180 kicks as they are very moderate and won't change the necessarily induce any large skill gaps. 

Regarding 180 spin without kicks (like the two rotation macro), for the people that use 180s in stacking like I do, this would be a nice quality of life change. When stacking normally, at the highest levels at least, people will stack to lower the needed inputs. If someone's stacking is adapted to 180s, but now they have to press twice, it is like a mind clog. Ideally they (me) will have to re-adapt to a slightly different stacking style to minimize placements that need to be flipped 180 in favor of simpler 1 rotation spots.

**Comment by LastExceed** [comment]
I think the obvious solution here is to make it a room option with multiple kick tables to choose from, defaulting to macro-like behaviour in order to stay compatible with existing leaderboards

**Comment by alex-ong** [comment]
I've noticed that you've pinned this issue.
At most, 30% of jstris players use 180° rotate (it's probably closer to 5%). 100% of Finesse and Keytris and Typomino use column teleportation so I think you should pin and address that issue first. While I agree that some features should have pro player opinions as core thoughts, the other feature has 100% pros as their userbase and so they are a vocal pro majority. This issue is run by a vocal pro minority.
https://github.com/o5k/tetrio-issues/issues/75

**Comment by o5k** [comment]
Please try out the newest build, **0.6.0-pre0**, in which 180s are available in custom games (solo and multi). Let me know what you think.

**Comment by o5k** [comment]
180s are now fully enabled across all modes from **0.8.0** onward, but may be removed again if feedback is negative. I'm closing the issue, but do not feel afraid to keep talking here and in Discord about the feature and giving feedback!
