### ISSUE TITLE
ASC Kick table doesn't include O piece

### ISSUE THREAD

**Issue by FugEbinMeme** [o5k/tetrio-issues#175]
O Piece doesn't rotate in tetrio's ASC kick table setting. If you play play ascension, the O piece very much rotates and has kicks.

**Comment by LayneTheEpic** [comment]
Is this a joke or..? Post a video of the O piece kicking

**Comment by FugEbinMeme** [comment]
> 
> 
> Post a video of an O piece kicking

https://www.youtube.com/watch?v=rofUhXFNHYI
No piece in asc is given special treatment. O gets the same 20 kicks that an L does. Or any conceivable piece possible within a 5x5 grid. All get the same kicks.

**Comment by LayneTheEpic** [comment]
Well I'll be damned, that's actually really cool and seems like it could be useful in a real game (compared to just "theory" that never gets applied)

**Comment by Oshisaure** [comment]
Since this issue is about making ASC accurate to the game it comes from, I'll add that the base rotation of the I piece isn't accurate to the original game either.

Both O and I (as well as everything else in this game evidently) define their base rotation by rotating the entire 5x5 bounding box they're defined in. This leads to one of I's blocks being stationary and the rest rotating around it, unlike the base rotations of the I piece in SRS.

Fumen in case that makes no sense: http://fumen.zui.jp/?m115@igzhIfRP1lA03tTASosaEFbssCSd88ADoo2Ai3eeEv?E98Awd0TASoStCjAAAAQgwhIewhGeRaAeQaHewh/epveQgQ?aIeQaHewhAexhGeQa/eB0eagwhHeQaAeRaGewhIewh1eZve?

**Comment by o5k** [comment]
![](https://kagari.moe/:/2020-05-05_16-21-13.gif)

Added in next patch.
