### ISSUE TITLE
Further 4-wide nerf?

### ISSUE THREAD

**Issue by Ads20000** [o5k/tetrio-issues#262]
### Is your feature request related to a problem? Please describe.
Was discussing with people in the tetr.io Quick Play chat and some (not all) reckoned c4w has been nerfed but not side four wide. Is there a way that 4-widing could be further nerfed? Is this necessary?

### Describe the solution you'd like
I'm not completely sure, I hope this Issue starts a discussion on this (hosted on this Issue) so that the necessity (or lack thereof) and nature of a further nerf could be thrashed out, but I would think that, if this is widely considered a problem, then the combo table would need to be further adjusted in some way, perhaps going for something like [King of Stackers' Exclusive+ combo table](https://kingofstackers.com/help.php) where it goes up in garbage and then back down (i.e. heads below three (or even two) rather than stays at three as at current), which presumably nerfs very long (i.e. usually 4-wide) combos?

KoS table:
![King of Stackers' combo table](https://user-images.githubusercontent.com/3178485/79077566-91529c80-7cfa-11ea-932e-7801d2513e42.png)

Current tetr.io table:
![2020-04-08_14-28-20](https://user-images.githubusercontent.com/3178485/79077662-18a01000-7cfb-11ea-8425-fd02458d86b2.png)

### Describe alternatives you've considered
Leave it as it is and let people deal with it (which personally I would consider to be perhaps a missed opportunity as tetr.io has one of the most 4w-nerfing combo tables which is an excellent USP and what drew me here, and also is a benefit of not being a Tetris game), or maybe 4w has been successfully nerfed and the people saying otherwise in chat regarding side four-wide are wrong (which would be fine if true, I hope this Issue, in the comments below, can decide this!)!!

### Additional context
I've only just started playing tetr.io (am Ads20000 on there too; having entered into Tetris via PuyoPuyo Tetris on Switch; I'm not very good (>7000 rating on Switch PPT, [about 10 APM on Jstris...](https://jstris.jezevec10.com/u/Ads20000))!) so please ignore me if I'm wrong but I'm hoping this would be a helpful place for a discussion on the (potential) issue. One of the draws for me, of tetr.io, was the existing 4w nerf! I also like how well-made the game is, am looking forward to the ranked mode going public! :D

**Comment by o5k** [comment]
It's been nerfed twice now, and at this point an 18-combo 4wide sends 33 lines as opposed to the guideline 64..Right now to make 4w viable you need to give it a continuation.

**Comment by GlitchyPSIX** [comment]
I personally don't think it should be nerfed further because continuing this line of nerfing it may come to a point where 4-wides do negative garbage (attack *yourself*)

4 wides are now only very viable against moderate players if you are smart about them, not just braindead single clearing prepared from the start of the game as a center 4wide and I honestly find that cool (within the "moderate players", me included, as I've had a few c4wers against me and I won).

Can't alienate that either.

**Comment by alex-ong** [comment]
> continuing this line of nerfing it may come to a point where 4-wides do negative garbage (attack _yourself_)

That's what it does in jstris big room. It's great.

One potential problem is the dreaded 4w into tetris, which is a killer move and can happen with a bit less than 4/10 chance

**Comment by Ads20000** [comment]
> It's been nerfed twice now, and at this point an 18-combo 4wide sends 33 lines as opposed to the guideline 64..Right now to make 4w viable you need to give it a continuation.

Yeah no worries, further nerfing may not be appropriate, like I say, this is a discussion topic for the issue.

> I personally don't think it should be nerfed further because continuing this line of nerfing it may come to a point where 4-wides do negative garbage (attack _yourself_)

I don't know how that actually works lol xD

**Comment by csq-curiosity** [comment]
> One potential problem is the dreaded 4w into tetris, which is a killer move and can happen with a bit less than 4/10 chance.

I think one potential solution in this context is to make the combo-induced damage to be additive, and variable depending on what type of line clears you perform. For example, set additive garbage as 0, 0, 1 as the default for any given 0, 1, 2 combo. Then,

single: 0
double: 1
triple: 2
quad: 4
TSSM: 0
TSS: 2
TSD: 4
TST: 6
B2B bonus: 1
All clear: 10
(for 3 combo and above)
single combo: +0.1
double combo: +0.2
triple combo: +0.5
quad combo: +1
TSSM combo: +0.2
TSS combo: +0.5
TSD combo: +1
TST combo: +1.5

The combo sum is counted until the combo ends, and any decimals will be rounded down.

In a system like this, an 8-combo ending with a quad results in 0 + 0 + 1 + 1(~~.1~~) + 1(~~.2~~) + 1(~~.3~~) + 1(~~.4~~) + 1(~~.5~~) + 4(+1 ~~.5~~) = 10 garbage lines, compared to a whopping 20 garbage in the current system.

This system would effectively butcher combo attacks by 4 widing, but it's not the only thing that this system kills. Changing combo tables like this inevitably affects downstacking attempts, too. This is really important, because once your stack is high, there is likely not much you can do if combos are further nerfed this way, and would make for impressive combacks to be even more difficult if at all possible. So, I do think this system is worth considering, but to also be done carefully

**Comment by LayneTheEpic** [comment]
That might work, but I think singles should probably add like +0.15, doubles +0.25, and round up just so it's not _as_ brokenly nerfed.

**Comment by o5k** [comment]
4wide is very harshly nerfed already, I feel any further nerfs would make downstacking unviable as well and/or combos entirely. I do not believe 4wide needs to be nerfed any more, but let me know if some killer strategy arrives using 4wide that isn't reliant on the opponent happening to send garbage and it happening to enter in the right column.

**Comment by Ads20000** [comment]
No worries thank you @o5k for engaging with and closing this thread! As I said in my OP, I was hoping to provide a place for discussion, so whilst I believe `wontfix` is the correct resolution here, I hope anyone who dissents feels able to come and comment here to make their case, particularly for:

> if some killer strategy arrives using 4wide that isn't reliant on the opponent happening to send garbage and it happening to enter in the right column.

**Comment by LayneTheEpic** [comment]
Honestly, nerfing further just ruins downstack, I think it's fine how it is

**Comment by Ads20000** [comment]
It's been raised to my attention that downstacking is becoming considered to be more broken, and also that 4w is also broken 'in the right hands' but I haven't managed to persuade the person I was speaking to to come here to elaborate :( The case that downstacking is broken is not one I'd naturally agree with but I know there was a recent Jstris tournament which nerfed downstacking combos as it was apparently widely considered broken there (though not sure they have a nerfed table like Tetrio?) and apparently also in late-game TEC... If anyone has any thoughts on this would be good to hear them! :)

**Comment by Ads20000** [comment]
![Screenshot from 2021-06-13 03-21-52](https://user-images.githubusercontent.com/3178485/121793466-1d11d280-cbf7-11eb-8096-ad9fe87f6abb.png)

(From WPL PPT Open [#]9 Twitch chat)

**Comment by limgw1** [comment]
> 4wide is very harshly nerfed already, I feel any further nerfs would make downstacking unviable as well and/or combos entirely. I do not believe 4wide needs to be nerfed any more, but let me know if some killer strategy arrives using 4wide that isn't reliant on the opponent happening to send garbage and it happening to enter in the right column.

hi
