### ISSUE TITLE
Aggressively zooming in the browser breaks WebGL

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#5]
Takes some time to repro, but holding down control and spamming mousewheel for a while seems to crash WebGL. Console: `WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`. At the very least, suspend the game or display an error if this happens.

Windows 10, Chrome 80

**Comment by o5k** [comment]
There's very little I can do about a lost context. Zooming in and out causes full repaints, so the browser is probably dropping the context because of resource exhaustion. I've added a warning dialog that will ask people to reload or try to continue for now, but there's little else I can do.

![WebGL error box](https://kagari.moe/:/2020-02-07_13-12-19.png)
